[2024-07-05 02:01:57 +0800] [3275306] [INFO] Starting gunicorn 22.0.0
[2024-07-05 02:01:57 +0800] [3275306] [INFO] Listening at: http://127.0.0.1:8004 (3275306)
[2024-07-05 02:01:57 +0800] [3275306] [INFO] Using worker: sync
[2024-07-05 02:01:57 +0800] [3275307] [INFO] Booting worker with pid: 3275307
[2024-07-05 02:01:57 +0800] [3275307] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lgmsadmin/anaconda3/envs/lgmnew2024/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
[2024-07-05 02:01:57 +0800] [3275307] [INFO] Worker exiting (pid: 3275307)
[2024-07-05 02:01:57 +0800] [3275306] [ERROR] Worker (pid:3275307) exited with code 3
[2024-07-05 02:01:57 +0800] [3275306] [ERROR] Shutting down: Master
[2024-07-05 02:01:57 +0800] [3275306] [ERROR] Reason: Worker failed to boot.
